### PR TITLE
Compatibility with MongoDB ODM

### LINKED ISSUE #3: Is this Doctrine bundle compatible with ODM as well?
To be used with MongoDB for instance: http://doctrine-mongodb-odm.readthedocs.org/en/latest/

### PR DESCRIPTION
**Pull request by alcaeus**
Closes #3.

This PR removes all hardcoding of `EntityManager` in favor of the `ObjectManager` interface from Doctrine Common, ensuring compatibility with multiple mappers. This allows for keeping most of the logic within one event subscriber instead of having to duplicate it. The event subscriber can be attached to either ORM or ODM and can handle being attached to both at the same time.

There are a few of things I still want to work on:
- [x] ~~The indexer at the moment contains a state, meaning it needs to store the object manager in order to later index the object in questions, I'd like to remove that~~ (skipped)
- [x] There is still some type checking in the subscriber to ensure compatibility to both ORM and ODM. I'd prefer this logic being in an event adapter, or even better, the events being compatible across ORM and ODM
- [x] Currently, tests only work with ORM. I'd like to extend them to ODM so the travis job can test indexing against both an SQL database as well as MongoDB.

Note: since this is a BC break which requires a major version change, this would go great in tandem with #53.

### CODE REVIEW

**Comment by maxiloc** [comment]
@alcaeus, Sorry for the late answer. That's looks really good.
You can for sure move forward with the two last points. Ping us when the first point `(The indexer at the moment contains a state, meaning it needs to store the object manager in order to later index the object in questions, I'd like to remove that)` is done and we'll start to review it.
Agree with you that merging #53 would be a good timing.

**Comment by alcaeus** [comment]
@maxiloc Unfortunately, extracting the `ObjectManager` from the Indexer is not as easy as I'd hoped. I'm not sure how well this will work when two object managers are in play (since both ORM and ODM can be used at the same time); I'll have to run some more tests with this.

**Comment by alcaeus** [comment]
@maxiloc Done. Tests fail on travis due to the missing secrets but run locally:

```
$ vendor/bin/phpunit
PHPUnit 4.8.27 by Sebastian Bergmann and contributors.

..........S.....S...............30 entities indexed
.30 entities indexed
.30 entities indexed
............................... 65 / 78 ( 83%)
......30 entities indexed
.30 entities indexed
.30 entities indexed
....

Time: 3.3 minutes, Memory: 40.50MB

OK, but incomplete, skipped, or risky tests!
Tests: 77, Assertions: 173, Skipped: 2.
```

**Comment by maxiloc** [comment]
@alcaeus Thanks, we'll have a look asap

**Comment by alcaeus** [comment]
@maxiloc Is there any chance to have this merged anytime soon?

**Comment by rayrutjes** [comment]
@alcaeus we have plans to support ODM in a future release. We might want to merge this in the meantime given it has been around for quite some time.

@julienbourdeau let us know when you have a moment to take a look.

Thank you all for your patience.

**Comment by alcaeus** [comment]
@rayrutjes Thanks for the updated. Rebased commits to fix conflicts.

**Comment by julienbourdeau** [comment]
Would you mind rebasing one last time and I can merge this one otherwise I'll merge the `odm` branch.

Thanks again!

**Comment by julienbourdeau** [comment]
@alcaeus When you rebase, can you remove the merge commit I just pushed. The _resolve conflicts_ feature didn't work as I expected -_- Sorry about that!

**Comment by rayrutjes** [comment]
@julienbourdeau feel free to rebase on your side, you don't need to bother @alcaeus :) 
Let me know if I can help.

**Comment by alcaeus** [comment]
@rayrutjes @julienbourdeau No worries - rebased, resolved conflicts and removed the merge commit. 👍

**Comment by julienbourdeau** [comment]
🎉 Thanks Andreas!

**Pull request merged**
