### PR TITLE
Implement connection timeout for Algolia connection

### PR DESCRIPTION
**Pull request by jupeter**
After bugs like that:
http://www.devsplanet.com/question/35693340

### CODE REVIEW

**Comment by rayrutjes** [comment]
Hi @jupeter, thank you so much for contributing!

Actually not sure exposing the timeouts is a good idea. Indeed the PHP API Client as some fallback mechanism that will be triggered when timeouts are reached to re-try on different hosts.

In your case I think you should rather investigate why you are having slow connecting to Algolia servers because >2s is not acceptable.

I'm afraid that if we expose the timeout, we decrease the overall reliability of the client's fallback mechanism.

WDYT?

**Comment by jupeter** [comment]
Hi @rayrutjes. 
My problem is related with dev environment. 
I got slow VM and when I pushed more than 500 records, it's trigger timeout error. 

I know that in production it's not acceptable - but for dev/test env is not possible to omit problem, like slow connection or weak hardware. 

Could you consider such usage-case? Maybe not documented feature can be acceptable?

Is TraviCI check fail is related with my PR or you got problem with tests?

**Comment by rayrutjes** [comment]
@jupeter I get your point about dev environment but I still feel 2s is a lot and that you have probably other issues going on that would make your developer's life easier if fixed. @maxiloc what do you think?

Regarding Travis, don't worry, the tests fail because forks have no access to encrypted keys for security reasons. We have to trigger tests on our side.

**Comment by hugorferreira** [comment]
This solution resolved a problem i had with Algolia because of my VB connection so slow that i was getting timeouts all the time.

**Comment by rayrutjes** [comment]
@jupeter ,any chance you could:
- [ ] Add tests
- [ ] Make sure we don't introduce any BC
- [ ] Rebase

I'll close this for now, feel free to re-push with the missing points.

Thanks for your support and your patience.

**Pull request closed without merging**
