### PR TITLE
connection timeout by @Jupeter

### PR DESCRIPTION
**Pull request by julienbourdeau**
New pull request to check travis build

See #104

### CODE REVIEW

**Comment by jupeter** [comment]
Looks OK :+1:

**Comment by bonswouar** [comment]
What happened to this feature ?!

**Comment by nunomaduro** [comment]
@bonswouar What do you mean?

**Comment by bonswouar** [comment]
@nunomaduro I don't see any `timeout` parameter on `master` branch, did I miss something ?

**Pull request merged**
