### PR TITLE
Add possibility to generate a dynamic index name

### PR DESCRIPTION
**Pull request by gregquat**

### CODE REVIEW

**Comment by gregquat** [comment]
@maxiloc , is there a problem with the parameter.yml file? Or did I do something wrong? (I ran the tests manually and everything was ok)
Thanks

**Comment by gregquat** [comment]
This does not work with the ReindexCommand. In this command, the indexName is not retrieved from a persisted entity but from an empty object (new Entity()).

So, in our case, it causes an issue as the getIndexName() method returns a "$this->getName()", and $name is empty.

I'm looking for a fix for that

**Comment by redox** [comment]
Hey @gregquat,

thank you for contributing. @maxiloc is in vacations but I'm sure he will take care of this PR next week!

**Comment by gregquat** [comment]
Don't merge it for the moment as there are some issues with the bulk actions.
I should find another solution and close the PR, or fix the PR before you can accept it.

**Comment by gregquat** [comment]
Too much side effects. Another solution has been found with the manual indexer.

**Pull request closed without merging**
